// Generated by CoffeeScript 1.9.3
$(function() {
  var getUrlVars;
  getUrlVars = function() {
    var parts, vars;
    vars = {};
    console.log(window.location.href);
    parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m, key, value) {
      var container, name, span;
      vars[key] = value;
      if (value === "hawk" || value === "panda" || value === "dolphin" || value === "fox") {
        container = document.getElementById('spiritAnimal');
      } else if (value === "black" || value === "red" || value === "blue" || value === "pink") {
        container = document.getElementById('backgroundColor');
      } else {
        container = document.getElementById('fontFamily');
      }
      span = document.createElement('span');
      console.log(vars[key]);
      name = document.createTextNode(vars[key]);
      span.appendChild(name);
      container.appendChild(span);
    });
    return vars;
  };
  return getUrlVars()['result'];
});
